### ISSUE TITLE
set_from_svo_file() does not work on Windows

### ISSUE THREAD

**Issue by JesperChristensen89** [stereolabs/zed-python-api#138] opened 2020-02-23 15:59 UTC
On Windows 10 with newest SDK (downloaded installed this week). Works on Linux.

Code snippet to reproduce:

```python
import pyzed.sl as sl
import numpy as np
import cv2
from datetime import datetime

if __name__ == "__main__":
    path = "test.svo"

    init_params  = sl.InitParameters()
    init_params.input.set_from_svo_file(path)
    init_params.svo_real_time_mode = False
    init_params.depth_mode = sl.DEPTH_MODE.QUALITY
    init_params.coordinate_units = sl.UNIT.MILLIMETER  # Use milliliter units (for depth measurements)
```

**Comment by adujardin** [comment] 2020-02-25 15:44
The input struct is tricky to use, it's either :
```python
input_t = sl.InputType()
input_t.set_from_svo_file(path)
init_params.input = input_t
```
or directly like this :
```python
 init_params.set_from_svo_file(path)
```
Otherwise, the value is discarded in a temporary object. This is caused by Cython and the need to match the C++ API.

However, it's true that there was a problem in the export_svo sample which is now fixed https://github.com/stereolabs/zed-examples/commit/3c035a711f9bce7250f38346c80ddfd9afd140bd

**Closed by adujardin** 2020-02-25 15:44 UTC
